export const EMAIL_REGEX =
  /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
export const PASSWORD_REGEX =
  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{5,}$/;
export const HELSINKI_LIVE_URL = 'https://stream.radio.co/s435d71fd8/listen';
export const TALLINN_LIVE_URL = 'https://streams.radio.co/s053b51423/listen';
export const LIVE_SHOWS_URL = 'https://ida-proxy.fly.dev/live';
export const LATEST_SHOWS_URL =
  'https://admin.idaidaida.net/wp-json/ida/v3/episodes?paged=1&posts_per_page=36';
export const TODAYS_SCHEDULE_URL =
  'https://admin.idaidaida.net/wp-json/ida/v3/todays-shows';
export const FULL_SCHEDULE_URL = 'https://ida-proxy.fly.dev/schedule';

export const GENRE_OPTIONS = [
  {label: '(ART)TALK', value: '(art)talk'},
  {label: '2 STEP', value: '2-step'},
  {label: '2-STEP', value: '2-step'},
  {label: 'abstract', value: 'abstract'},
  {label: 'academic music', value: 'academic-music'},
  {label: 'acid', value: 'acid'},
  {label: 'acid jazz', value: 'acid-jazz'},
  {label: 'ACID TECHNO', value: 'acid-techno'},
  {label: 'Acousmatic', value: 'acousmatic'},
  {label: 'acoustic', value: 'acoustic'},
  {label: 'africa', value: 'africa'},
  {label: 'African', value: 'african'},
  {label: 'afro', value: 'afro'},
  {label: 'afrobeat', value: 'afrobeat'},
  {label: 'Afropop', value: 'afropop'},
  {label: 'alternative', value: 'alternative'},
  {label: 'alternative rock', value: 'alternative-rock'},
  {label: 'Amapiano', value: 'amapiano'},
  {label: 'Ambient', value: 'ambient'},
  {label: 'AMBIENT TECHNO', value: 'ambient-techno'},
  {label: 'analog', value: 'analog'},
  {label: 'anti-club', value: 'anti-club'},
  {label: 'AOR', value: 'aor'},
  {label: 'ART METAL', value: 'art-metal'},
  {label: 'ART MUSIC', value: 'art-music'},
  {label: 'ART PUNK', value: 'art-punk'},
  {label: 'ART ROCK', value: 'art-rock'},
  {label: 'ART-FOLK', value: 'art-folk'},
  {label: 'ART-POP', value: 'art-pop'},
  {label: 'ATMOSPHERIC DRUM & BASS', value: 'atmospheric-drum-bass'},
  {label: 'Avant Garde Metal', value: 'avant-garde-metal'},
  {label: 'avant-club', value: 'avant-club'},
  {label: 'avant-garde', value: 'avant-garde'},
  {label: 'baile funk', value: 'baile-funk'},
  {label: 'BALEARIC', value: 'balearic'},
  {label: 'ballroom', value: 'ballroom'},
  {label: 'Bardcore', value: 'bardcore'},
  {label: 'bass', value: 'bass'},
  {label: 'BE-BOP', value: 'be-bop'},
  {label: 'beatlesque', value: 'beatlesque'},
  {label: 'beats', value: 'beats'},
  {label: 'Black Metal', value: 'black-metal'},
  {label: 'bleep', value: 'bleep'},
  {label: 'BLUEGRASS', value: 'bluegrass'},
  {label: 'BLUES', value: 'blues'},
  {label: 'Bmore Club', value: 'bmore-club'},
  {label: 'boogaloo', value: 'boogaloo'},
  {label: 'boogie', value: 'boogie'},
  {label: 'books', value: 'books'},
  {label: 'BOSSA NOVA', value: 'bossa-nova'},
  {label: 'brazil', value: 'brazil'},
  {label: 'brazilian', value: 'brazilian'},
  {label: 'breakbeat', value: 'breakbeat'},
  {label: 'Breaks', value: 'breaks'},
  {label: 'broken beat', value: 'broken-beat'},
  {label: 'chillhop', value: 'chillhop'},
  {label: 'chillout', value: 'chillout'},
  {label: 'chillwave', value: 'chillwave'},
  {label: 'choir', value: 'choir'},
  {label: 'Christmas', value: 'christmas'},
  {label: 'cinematic', value: 'cinematic'},
  {label: 'CLASSICAL', value: 'classical'},
  {label: 'club', value: 'club'},
  {label: 'cold wave', value: 'cold-wave'},
  {label: 'Contemporary', value: 'contemporary'},
  {label: 'cosmic americana', value: 'cosmic-americana'},
  {label: 'COUNTRY', value: 'country'},
  {label: 'cumbia', value: 'cumbia'},
  {label: 'dance', value: 'dance'},
  {label: 'dancehall', value: 'dancehall'},
  {label: 'DARK AMBIENT', value: 'dark-ambient'},
  {label: 'dark jazz', value: 'dark-jazz'},
  {label: 'darkwave', value: 'darkwave'},
  {label: 'death metal', value: 'death-metal'},
  {label: 'DECONSTRUCTED CLUB', value: 'deconstructed-club'},
  {label: 'Deep House', value: 'deep-house'},
  {label: 'Deep Techno', value: 'deep-techno'},
  {label: 'Detroit', value: 'detroit'},
  {label: 'disco', value: 'disco'},
  {label: 'diva house', value: 'diva-house'},
  {label: 'donk', value: 'donk'},
  {label: 'doom', value: 'doom'},
  {label: 'Downtempo', value: 'downtempo'},
  {label: 'dream pop', value: 'dream-pop'},
  {label: 'drill', value: 'drill'},
  {label: 'Drone', value: 'drone'},
  {label: 'DRUM & BASS', value: 'drum-bass'},
  {label: 'drumfunk', value: 'drumfunk'},
  {label: 'dub', value: 'dub'},
  {label: 'dub reggae', value: 'dub-reggae'},
  {label: 'dub techno', value: 'dub-techno'},
  {label: 'DUBSTEP', value: 'dubstep'},
  {label: 'dusty fingers', value: 'dusty-fingers'},
  {label: 'early-dancehall', value: 'early-dancehall'},
  {label: 'easy listening', value: 'easy-listening'},
  {label: 'ebm', value: 'ebm'},
  {label: 'eclectic', value: 'eclectic'},
  {label: 'edm', value: 'edm'},
  {label: 'education', value: 'education'},
  {label: 'ELECTRO', value: 'electro'},
  {label: 'electro acoustic', value: 'electro-acoustic'},
  {label: 'Electro House', value: 'electro-house'},
  {label: 'electroacoustic', value: 'electroacoustic'},
  {label: 'ELECTRONIC', value: 'electronic'},
  {label: 'electronica', value: 'electronica'},
  {label: 'EMO', value: 'emo'},
  {label: 'environment', value: 'environment'},
  {label: 'Esoteric', value: 'esoteric'},
  {label: 'Estonian', value: 'estonian'},
  {label: 'Estrada', value: 'estrada'},
  {label: 'Ethereal', value: 'ethereal'},
  {label: 'eurodance', value: 'eurodance'},
  {label: 'experimental', value: 'experimental'},
  {label: 'EXPERIMENTAL ELECTRONICA', value: 'experimental-electronica'},
  {label: 'EXPERIMENTAL ROCK', value: 'experimental-rock'},
  {label: 'field', value: 'field'},
  {label: 'field recordings', value: 'field-recordings'},
  {label: 'first wave punk', value: 'first-wave-punk'},
  {label: 'FOLK', value: 'folk'},
  {label: 'folk rock', value: 'folk-rock'},
  {label: 'FOOTWORK', value: 'footwork'},
  {label: 'Fourth World', value: 'fourth-world'},
  {label: 'FUNK', value: 'funk'},
  {label: 'funk metal', value: 'funk-metal'},
  {label: 'G-FUNK', value: 'g-funk'},
  {label: 'gabba', value: 'gabba'},
  {label: 'GABBER', value: 'gabber'},
  {label: 'GARAGE', value: 'garage'},
  {label: 'Genrefluid', value: 'genrefluid'},
  {label: 'GHETTO', value: 'ghetto'},
  {label: 'Ghettotech', value: 'ghettotech'},
  {label: 'GLAM', value: 'glam'},
  {label: 'Glitch', value: 'glitch'},
  {label: 'global bass', value: 'global-bass'},
  {label: 'gospel', value: 'gospel'},
  {label: 'Gothic', value: 'gothic'},
  {label: 'gothic rock', value: 'gothic-rock'},
  {label: 'Gqom', value: 'gqom'},
  {label: 'grime', value: 'grime'},
  {label: 'groove', value: 'groove'},
  {label: 'Grunge', value: 'grunge'},
  {label: 'GUEST MIX', value: 'guest-mix'},
  {label: 'guilty pleasure', value: 'guilty-pleasure'},
  {label: 'habibi funk', value: 'habibi-funk'},
  {label: 'handbag house', value: 'handbag-house'},
  {label: 'HARD BOP', value: 'hard-bop'},
  {label: 'HARD HOUSE', value: 'hard-house'},
  {label: 'HARD ROCK', value: 'hard-rock'},
  {label: 'hard techno', value: 'hard-techno'},
  {label: 'HARDCORE', value: 'hardcore'},
  {label: 'hardstyle', value: 'hardstyle'},
  {label: 'heartbeat', value: 'heartbeat'},
  {label: 'HEAVY METAL', value: 'heavy-metal'},
  {label: 'Hi-NRG', value: 'hi-nrg'},
  {label: 'HIP HOUSE', value: 'hip-house'},
  {label: 'hip-hop', value: 'hip-hop'},
  {label: 'House', value: 'house'},
  {label: 'HYBRID', value: 'hybrid'},
  {label: 'idm', value: 'idm'},
  {label: 'Illbient', value: 'illbient'},
  {label: 'INDIAN MUSIC', value: 'indian-music'},
  {label: 'indie', value: 'indie'},
  {label: 'indie rock', value: 'indie-rock'},
  {label: 'industrial', value: 'industrial'},
  {label: 'INSTRUMENTAL', value: 'instrumental'},
  {label: 'italo', value: 'italo'},
  {label: 'J-Pop', value: 'j-pop'},
  {label: 'japan', value: 'japan'},
  {label: 'JAZZ', value: 'jazz'},
  {label: 'JAZZ-FUNK', value: 'jazz-funk'},
  {label: 'Jersey Club', value: 'jersey-club'},
  {label: 'JUKE', value: 'juke'},
  {label: 'JUNGLE', value: 'jungle'},
  {label: 'JUNK', value: 'junk'},
  {label: 'k-pop', value: 'k-pop'},
  {label: 'kuduro', value: 'kuduro'},
  {label: 'latin', value: 'latin'},
  {label: 'left field', value: 'left-field'},
  {label: 'leftfield', value: 'leftfield'},
  {label: 'Library', value: 'library'},
  {label: 'library music', value: 'library-music'},
  {label: 'LIQUID', value: 'liquid'},
  {label: 'LIVE', value: 'live'},
  {label: 'LIVE MUSIC', value: 'live-music'},
  {label: 'Lo-fi', value: 'lo-fi'},
  {label: 'LOUNGE', value: 'lounge'},
  {label: 'LOVERS ROCK', value: 'lovers-rock'},
  {label: 'Mellow', value: 'mellow'},
  {label: 'memphis', value: 'memphis'},
  {label: 'MEMPHIS', value: 'memphis'},
  {label: 'METAL', value: 'metal'},
  {label: 'micro-house', value: 'micro-house'},
  {label: 'minimal', value: 'minimal'},
  {label: 'minimal wave', value: 'minimal-wave'},
  {label: 'Minimalism', value: 'minimalism'},
  {label: 'MISC', value: 'misc'},
  {label: 'Modern classical', value: 'modern-classical'},
  {label: 'modern soul', value: 'modern-soul'},
  {label: 'MODULAR', value: 'modular'},
  {label: 'movies', value: 'movies'},
  {label: 'multigenre', value: 'multigenre'},
  {label: 'Musique concrète', value: 'musique-concrète'},
  {label: 'neo soul', value: 'neo-soul'},
  {label: 'NEOCLASSICAL', value: 'neoclassical'},
  {label: 'new age', value: 'new-age'},
  {label: 'new beat', value: 'new-beat'},
  {label: 'NEW CLASSICAL', value: 'new-classical'},
  {label: 'new wave', value: 'new-wave'},
  {label: 'nightcore', value: 'nightcore'},
  {label: 'No Wave', value: 'no-wave'},
  {label: 'Noise', value: 'noise'},
  {label: 'noise rock', value: 'noise-rock'},
  {label: 'Nostalgic', value: 'nostalgic'},
  {label: 'nu disco', value: 'nu-disco'},
  {label: 'nu metal', value: 'nu-metal'},
  {label: 'old skool', value: 'old-skool'},
  {label: 'organic', value: 'organic'},
  {label: 'OTHER', value: 'other'},
  {label: 'OUTSIDER MUSIC', value: 'outsider-music'},
  {label: 'performance', value: 'performance'},
  {label: 'Philly Club', value: 'philly-club'},
  {label: 'PHONK', value: 'phonk'},
  {label: 'poetry', value: 'poetry'},
  {label: 'Pop', value: 'pop'},
  {label: 'pop-rock', value: 'pop-rock'},
  {label: 'post-metal', value: 'post-metal'},
  {label: 'POST-PUNK', value: 'post-punk'},
  {label: 'Post-rock', value: 'post-rock'},
  {label: 'progressive', value: 'progressive'},
  {label: 'PROGRESSIVE METAL', value: 'progressive-metal'},
  {label: 'progressive rock', value: 'progressive-rock'},
  {label: 'PROTO-PUNK', value: 'proto-punk'},
  {label: 'Psybient', value: 'psybient'},
  {label: 'PSYCHEDELIC', value: 'psychedelic'},
  {label: 'psychedelic pop', value: 'psychedelic-pop'},
  {label: 'psychedelic rock', value: 'psychedelic-rock'},
  {label: 'PUNK', value: 'punk'},
  {label: 'PUNK ROCK', value: 'punk-rock'},
  {label: 'R&B', value: 'r&b'},
  {label: 'radiophonic', value: 'radiophonic'},
  {label: 'RAGGA', value: 'ragga'},
  {label: 'Rap', value: 'rap'},
  {label: 'rave', value: 'rave'},
  {label: 'reggae', value: 'reggae'},
  {label: 'Reggaeton', value: 'reggaeton'},
  {label: 'Relax', value: 'relax'},
  {label: 'rhythm & blues', value: 'rhythm-blues'},
  {label: 'Rock', value: 'rock'},
  {label: 'ROCKABILLY', value: 'rockabilly'},
  {label: 'rockstedy', value: 'rockstedy'},
  {label: 'ROMANTIC', value: 'romantic'},
  {label: 'roots', value: 'roots'},
  {label: 'roots reggae', value: 'roots-reggae'},
  {label: 'Salsa', value: 'salsa'},
  {label: 'seinast seina', value: 'seinast-seina'},
  {label: 'shoegaze', value: 'shoegaze'},
  {label: 'SKA', value: 'ska'},
  {label: 'slowcore', value: 'slowcore'},
  {label: 'soft rock', value: 'soft-rock'},
  {label: 'SOUL', value: 'soul'},
  {label: 'sound art', value: 'sound-art'},
  {label: 'SOUND COLLAGE', value: 'sound-collage'},
  {label: 'sound design', value: 'sound-design'},
  {label: 'Sound healing', value: 'sound-healing'},
  {label: 'soundtrack', value: 'soundtrack'},
  {label: 'soviet new wave', value: 'soviet-new-wave'},
  {label: 'soviet pop', value: 'soviet-pop'},
  {label: 'SPACE JAZZ', value: 'space-jazz'},
  {label: 'spanish pop', value: 'spanish-pop'},
  {label: 'SPEED GARAGE', value: 'speed-garage'},
  {label: 'spiritual', value: 'spiritual'},
  {label: 'spoken word', value: 'spoken-word'},
  {label: 'suomi', value: 'suomi'},
  {label: 'SYMPHONIC', value: 'symphonic'},
  {label: 'SYNTH', value: 'synth'},
  {label: 'synth-pop', value: 'synth-pop'},
  {label: 'Synth-Punk', value: 'synth-punk'},
  {label: 'synth-wave', value: 'synth-wave'},
  {label: 'Synthetic', value: 'synthetic'},
  {label: 'talk', value: 'talk'},
  {label: 'tech-house', value: 'tech-house'},
  {label: 'Techno', value: 'techno'},
  {label: 'toxic friends', value: 'toxic-friends'},
  {label: 'traditional', value: 'traditional'},
  {label: 'trance', value: 'trance'},
  {label: 'Trap', value: 'trap'},
  {label: 'Tribal', value: 'tribal'},
  {label: 'tribal house', value: 'tribal-house'},
  {label: 'Trill', value: 'trill'},
  {label: 'trip hop', value: 'trip-hop'},
  {label: 'UK', value: 'uk'},
  {label: 'Uk bass', value: 'uk-bass'},
  {label: 'UK Funky', value: 'uk-funky'},
  {label: 'UK GARAGE', value: 'uk-garage'},
  {label: 'UNDERGROUND', value: 'underground'},
  {label: 'vaporwave', value: 'vaporwave'},
  {label: 'varia', value: 'varia'},
  {label: 'various', value: 'various'},
  {label: 'Various to Specific', value: 'various-to-specific'},
  {label: 'WAVE', value: 'wave'},
  {label: 'West Coast', value: 'west-coast'},
  {label: 'WORLD', value: 'world'},
  {label: 'Yacht rock', value: 'yacht-rock'},
];
