name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Install node modules
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
